### ISSUE TITLE
Side of head of player model is broken in inventory screen.

### ISSUE THREAD

**Issue by TiLopes** [Creatomat/Better-Animations#13]
![image](https://github.com/Creatomat/Better-Animations/assets/106965010/def4c013-f3d3-4a1f-a8f8-ff9bc9c1c1ba)

I also want to add that the mod [3D Skin Layers](https://modrinth.com/mod/3dskinlayers) is currently unsupported since the player model is basically hidden with the texture pack.

**Comment by Creatomat** [comment]
Hello, first up, thanks for reporting this
Secondly, for 3d skin layers, go to the mod settings and disable '3d jacket'

**Comment by Creatomat** [comment]
I am unable to reproduce this bug

**Comment by TiLopes** [comment]
Here's a recording of the bug, I also show what mods I'm currently using in 1.20.1:

https://github.com/Creatomat/Better-Animations/assets/106965010/9914fece-23b6-422a-a721-411201e38999

**Comment by Creatomat** [comment]
Ill try debugging on 1.20.1 tho if it is a bug with 1.20.1 emf/etf i can't fix it

**Comment by TiLopes** [comment]
I'm also having the same issue on 1.20.4

**Comment by Creatomat** [comment]
What mods on 1.20.4, also then ill fix it in the next release

**Comment by Creatomat** [comment]
> I'm also having the same issue on 1.20.4

What mods on 1.20.4 and ill fix it in next release

**Comment by TiLopes** [comment]
These are the mods I'm using in 1.20.4
```
Mods:
  [✔] architectury-11.0.11-fabric
  [✔] BadOptimizations-1.6.3
  [✔] c2me-fabric-mc1.20.4-0.2.0+alpha.11.40
  [✔] cloth-config-13.0.121-fabric
  [✔] continuity-3.0.0-beta.4+1.20.2
  [✔] Controlling-fabric-1.20.4-15.0.2
  [✔] enhancedblockentities-0.9.1+1.20.2
  [✔] entity_model_features_fabric_1.20.4-1.2.3
  [✔] entity_texture_features_fabric_1.20.4-5.2.2
  [✔] entityculling-fabric-1.6.3.1-mc1.20.4
  [✔] exordium-fabric-1.2.1-mc1.20.4
  [✔] fabric-api-0.95.4+1.20.4
  [✔] fabric-language-kotlin-1.10.17+kotlin.1.9.22
  [✔] ferritecore-6.0.3-fabric
  [✔] ImmediatelyFast-Fabric-1.2.8+1.20.4
  [✔] indium-1.0.28+mc1.20.4
  [✔] inventorymanagement-1.5.0+1.20.3
  [✔] krypton-0.2.6
  [✔] lithium-fabric-mc1.20.4-0.12.1
  [✔] modernfix-fabric-5.12.1+mc1.20.4
  [✔] modmenu-9.0.0
  [✔] moreculling-1.20.4-0.22.0
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] NoChatReports-FABRIC-1.20.4-v2.5.0
  [✔] noisium-1.0.2+mc1.20.x
  [✔] notenoughanimations-fabric-1.7.0-mc1.20.4
  [✔] optigui-2.1.7
  [✔] reeses_sodium_options-1.7.2+mc1.20.4-build.102
  [✔] Resourcify (1.20.2+-fabric)-1.3.1
  [✔] seamless-2.2.2-fabric-1.20.4
  [✔] seamless-loading-screen-2.1.1+1.20.4-fabric
  [✔] Searchables-fabric-1.20.4-1.0.3
  [✔] sodium-extra-0.5.4+mc1.20.4-build.116
  [✔] sodium-fabric-0.5.8+mc1.20.4
  [✔] threadtweak-fabric-1.20.4-0.1.2
  [✔] vmp-fabric-mc1.20.4-0.2.0+beta.7.136-all
  [✔] XaerosWorldMap_1.37.8_Fabric_1.20.4
  [✔] yet-another-config-lib-fabric-3.3.2+1.20.4
  [✔] Zoomify-2.13.0
```

**Comment by Creatomat** [comment]
> 1.20.4

Got it

**Comment by Creatomat** [comment]
Can't reproduce, will be an issue with one of ur mod configs

**Comment by TiLopes** [comment]
Found the issue. It's a setting in 3D Player Skins called "Fast Render" it is turned on by default and if your skin makes use of transparent pixels it has that glitchy behavior, regardless of the texture pack. Just turning it off did the trick. Maybe adding this to the README might be helpful if anyone has the same issue.

**Comment by Creatomat** [comment]
Will do
