### ISSUE TITLE
Armor Clipping

### ISSUE THREAD

**Issue by LoogiCarry** [Creatomat/Better-Animations#14]
Armor is clipping through you when you walk

**Comment by LoogiCarry** [comment]
![obraz](https://github.com/Creatomat/Better-Animations/assets/84445776/a064d9e7-1dd1-4757-9572-6670926a30e8)
![obraz](https://github.com/Creatomat/Better-Animations/assets/84445776/d406eff5-2a99-41c0-ad8a-9d9a55d57475)

**Comment by Creatomat** [comment]
Will check into it asap
