### ISSUE TITLE
Compatibility for simply sneak?

### ISSUE THREAD

**Issue by PokeTlc** [Creatomat/Better-Animations#26]
If possible?

**Comment by Creatomat** [comment]
Prolly not, since it animates the player on its own, but imma try

**Comment by Creatomat** [comment]
after testing it, simplysneak is incompatible with entity model features itself, as a result, i cannot fix it, please report this bug here, peace

Report here if necessary: https://github.com/Traben-0/Entity_Model_Features/issues
