### ISSUE TITLE
Falling animation with Skin Shuffle

### ISSUE THREAD

**Issue by IntMarco** [Creatomat/Better-Animations#29]
https://modrinth.com/mod/skinshuffle
<img width="246" alt="Screenshot 2024-07-09 alle 21 25 33" src="https://github.com/Creatomat/Better-Animations/assets/124934175/536b95f4-abc1-4458-a2ea-b87751c11cdb">

**Comment by Creatomat** [comment]
I'll see if I can disable it for the npc there, but it's probably not possible, I'll report this issue to traben aswell

**Comment by IntMarco** [comment]
Perfect , ty

**Comment by IMB11** [comment]
> I'll see if I can disable it for the npc there, but it's probably not possible, I'll report this issue to traben aswell

SkinShuffle dev here, I could see if I could trick the model renderer into thinking the player is stationary, but I can't guarantee anything.

**Comment by Creatomat** [comment]
> > I'll see if I can disable it for the npc there, but it's probably not possible, I'll report this issue to traben aswell
> 
> SkinShuffle dev here, I could see if I could trick the model renderer into thinking the player is stationary, but I can't guarantee anything.

Thank u soo much

**Comment by Creatomat** [comment]
> > I'll see if I can disable it for the npc there, but it's probably not possible, I'll report this issue to traben aswell
> 
> SkinShuffle dev here, I could see if I could trick the model renderer into thinking the player is stationary, but I can't guarantee anything.

If It helps, the way player anime packs detect falling is basically checking if the height from the nearest block below the player is more than a certain value, so if u could just tell the renderer there's a block just below the player, it will fix the issue

**Comment by IMB11** [comment]
Okay, in the future you should probably check the player's velocity instead of doing that.

**Comment by Creatomat** [comment]
> Okay, in the future you should probably check the player's velocity instead of doing that.

I don't think entity model features has a way to check velocity and such

**Comment by Creatomat** [comment]
But now that you've given me the idea, imma have to look into it

**Comment by Creatomat** [comment]
no way to do it reliably, as of the latest version of emf on date of posting this message
